spring:
  application:
    name: management-systems
  datasource:
    url: jdbc:postgresql://host.docker.internal:5436/postgres?createDatabaseIfNotExist=true
#    url: jdbc:postgresql://localhost:5436/postgres?createDatabaseIfNotExist=true
    username: postgres
    password: password
  sql:
    init:
      mode: always
      platform: postgres
  jpa:
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true
server:
  port: 8074
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://host.docker.internal:8761/eureka}
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true